language: node_js
node_js:
  - "node"
  - "6"

script:
  - npm test
  - npm run coverage
  - npm run check-coverage

before_script:
  - export TZ=Canada/Eastern

after_success:
  - npm run report-coverage
